<?php

namespace TravelBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByHotelAttributs($nbRoom, $city = '', $stars = 1)
    {
        return $this->createQueryBuilder('h')
            ->select('h, COUNT(r.hotel) as nbroom')
            ->join('h.rooms', 'r')
            ->groupBy('r.hotel, h.id')
            ->having('nbroom>=:nbroom')
            ->setParameter('nbroom', $nbRoom)
            ->where('r.book = :book')
            ->setParameter('book', 0)
            ->andWhere('h.stars >= :stars')
            ->setParameter('stars', $stars)
            ->andWhere('h.city=:city')
            ->setParameter('city', $city)
            ->orderBy('nbroom', 'DESC')
            ->getQuery()->getResult();
    }
}
